Repository got-board-team/got-board-api-v2, pull requests merged in 2019-02, with the labels that each got.

#35 Rename Pusher event from bulk_update to bulk-update
  app/controllers/orders_controller.rb
Labels: enhancement, release-candidate

#34 Create a Territory table
  app/game_data/territories.yml
  app/interactions/games/fetch_territories.rb
  app/interactions/territories/import.rb
  app/models/game.rb
  app/models/game/territory.rb
  app/models/territory.rb
  app/serializers/territory_serializer.rb
  db/migrate/20180808175924_create_territories.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/games.rb
  spec/interactions/games/fetch_territories_spec.rb
  spec/interactions/territories/import_spec.rb
  spec/models/game/territory_spec.rb
  spec/models/game_spec.rb
  spec/serializers/territory_serializer_spec.rb
Labels: feature, release-candidate

#33 Change JSON serializer
  Gemfile
  Gemfile.lock
  app/controllers/games_controller.rb
  app/controllers/wildling_cards_controller.rb
  app/models/game.rb
  app/serializers/game_serializer.rb
  app/serializers/garrison_token_serializer.rb
  app/serializers/house_card_serializer.rb
  app/serializers/house_serializer.rb
  app/serializers/neutral_force_token_serializer.rb
  app/serializers/order_serializer.rb
  app/serializers/power_token_serializer.rb
  app/serializers/supply_token_serializer.rb
  app/serializers/territory_serializer.rb
  app/serializers/token_serializer.rb
  app/serializers/unit_serializer.rb
  app/serializers/victory_token_serializer.rb
  app/serializers/wildling_card_serializer.rb
  config/application.rb
  spec/requests/games_spec.rb
  spec/requests/wildling_cards_spec.rb
  spec/serializers/order_serializer_spec.rb
  spec/serializers/token_serializer_spec.rb
  spec/support/serializer_spec_helper.rb
Labels: Medium Priority, Next Release, performance

#36 Update Ruby and gems
  .travis.yml
  Gemfile
  Gemfile.lock
  spec/interactions/games/create_orders_spec.rb
Labels: Low Priority

#39 Update ruby to 2.6.1
  .travis.yml
  Gemfile
  Gemfile.lock
  README.md
Labels: feature, review
